import os
import shutil
import re
import sys
from pymatgen.io.xyz import XYZ
from pymatgen.core import Molecule

# You must have these functions in file_generator.py
from file_generator import submit_slurm_job, generate_job_sh, generate_lammps_input, write_artn_in

# Required files
REQUIRED_FILES = ["pot26.mtp", "mlip.ini"]

# Check for necessary files in current directory
for file in REQUIRED_FILES:
    if not os.path.exists(file):
        raise FileNotFoundError(f"Required file {file} not found!")

# Input: original .xyz file
if len(sys.argv) < 2:
    print("Usage: python script.py filename.xyz")
    sys.exit(1)

xyz_file = sys.argv[1]

# Read original molecule and extract lattice vectors
with open(xyz_file, "r") as f:
    lines = f.readlines()
    n_atoms = int(lines[0].strip())
    lattice_vectors = None
    
    if len(lines) > 1:
        match = re.search(r'Lattice="([^"]+)"', lines[1])
        if match:
            lattice_vectors = [float(x) for x in match.group(1).split()]

mol = XYZ.from_file(xyz_file).molecule

# Generate vacancies
for i in range(n_atoms):
    # Create new molecule with atom i removed
    new_species = [mol.species[j] for j in range(n_atoms) if j != i]
    new_coords = [mol.cart_coords[j] for j in range(n_atoms) if j != i]
    mol_vac = Molecule(new_species, new_coords)
    
    # Create folder for this vacancy
    folder = f"vac_{i}"
    os.makedirs(folder, exist_ok=True)
    
    # Save vacancy structure as XYZ
    xyz_path = os.path.join(folder, "mol_vac.xyz")
    mol_vac.to(fmt="xyz", filename=xyz_path)
    
    # Copy required files
    for file in REQUIRED_FILES:
        shutil.copy2(file, folder)
    
    # Create artn.in file
    write_artn_in(push_ids=n_atoms-1, filename=os.path.join(folder, "artn.in"))
    
    # Generate SLURM and LAMMPS files
    job_sh_path = os.path.join(folder, "script_job.sh")
    lammps_input_path = os.path.join(folder, "lammps.in")
    lmp_path = os.path.join(folder, "mol_vac.lmp")
    
    generate_job_sh(
        time="0-00:30:00",
        num_task=2,
        num_core=2,
        mem_per_cpu="4G",
        file_name=job_sh_path
    )
    
    generate_lammps_input(
        input_data_file="./mol_vac.lmp",
        output_file=lammps_input_path
    )
    
    # Write .lmp file
    with open(lmp_path, "w") as f:
        f.write("LAMMPS data file generated by script\n\n")
        f.write(f"{len(mol_vac)} atoms\n")
        
        unique_species = list({site.species_string for site in mol_vac})
        f.write(f"{len(unique_species)} atom types\n\n")
        
        # Write box dimensions
        if lattice_vectors and len(lattice_vectors) == 9:
            a, b, c = lattice_vectors[0:3], lattice_vectors[3:6], lattice_vectors[6:9]
            f.write(f"0.0 {a[0]:.6f} xlo xhi\n")
            f.write(f"0.0 {b[1]:.6f} ylo yhi\n")
            f.write(f"0.0 {c[2]:.6f} zlo zhi\n")
            f.write(f"{b[0]:.6f} {c[0]:.6f} {c[1]:.6f} xy xz yz\n\n")
        else:
            coords = mol_vac.cart_coords
            f.write(f"{coords[:,0].min()-5:.6f} {coords[:,0].max()+5:.6f} xlo xhi\n")
            f.write(f"{coords[:,1].min()-5:.6f} {coords[:,1].max()+5:.6f} ylo yhi\n")
            f.write(f"{coords[:,2].min()-5:.6f} {coords[:,2].max()+5:.6f} zlo zhi\n\n")
        
        # Write masses
        f.write("Masses\n\n")
        for idx, species in enumerate(unique_species, 1):
            mass = next(site.specie.atomic_mass for site in mol_vac if site.species_string == species)
            f.write(f"{idx} {mass:.4f}\n")
        
        # Write atomic coordinates
        f.write("\nAtoms # atomic\n\n")
        species_to_type = {species: idx+1 for idx, species in enumerate(unique_species)}
        for idx, site in enumerate(mol_vac, 1):
            atom_type = species_to_type[site.species_string]
            x, y, z = site.coords
            f.write(f"{idx} {atom_type} {x:.6f} {y:.6f} {z:.6f}\n")
    
    # Submit job
    os.chdir(folder)
    job_id = submit_slurm_job('script_job.sh')
    os.chdir("..")
    
    print(f"Vacancy {i}: Folder '{folder}' created and job submitted. Job ID: {job_id}")
